/* Generated by AN DISI Unibo */ 
package it.unibo.webguiexecutor;
import it.unibo.qactors.PlanRepeat;
import it.unibo.qactors.QActorContext;
import it.unibo.qactors.StateExecMessage;
import it.unibo.qactors.QActorUtils;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.action.AsynchActionResult;
import it.unibo.qactors.action.IActorAction;
import it.unibo.qactors.action.IActorAction.ActionExecMode;
import it.unibo.qactors.action.IMsgQueue;
import it.unibo.qactors.akka.QActor;
import it.unibo.qactors.StateFun;
import java.util.Stack;
import java.util.Hashtable;
import java.util.concurrent.Callable;
import alice.tuprolog.Struct;
import alice.tuprolog.Term;
import it.unibo.qactors.action.ActorTimedAction;
public abstract class AbstractWebguiexecutor extends QActor { 
	protected AsynchActionResult aar = null;
	protected boolean actionResult = true;
	protected alice.tuprolog.SolveInfo sol;
	protected String planFilePath    = null;
	protected String terminationEvId = "default";
	protected String parg="";
	protected boolean bres=false;
	protected IActorAction action;
	 
	
		protected static IOutputEnvView setTheEnv(IOutputEnvView outEnvView ){
			return outEnvView;
		}
		public AbstractWebguiexecutor(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
			super(actorId, myCtx,  
			"./srcMore/it/unibo/webguiexecutor/WorldTheory.pl",
			setTheEnv( outEnvView )  , "init");
			this.planFilePath = "./srcMore/it/unibo/webguiexecutor/plans.txt";
	  	}
		@Override
		protected void doJob() throws Exception {
			String name  = getName().replace("_ctrl", "");
			mysupport = (IMsgQueue) QActorUtils.getQActor( name ); 
			initStateTable(); 
	 		initSensorSystem();
	 		history.push(stateTab.get( "init" ));
	  	 	autoSendStateExecMsg();
	  		//QActorContext.terminateQActorSystem(this);//todo
		} 	
		/* 
		* ------------------------------------------------------------
		* PLANS
		* ------------------------------------------------------------
		*/    
	    //genAkkaMshHandleStructure
	    protected void initStateTable(){  	
	    	stateTab.put("handleToutBuiltIn",handleToutBuiltIn);
	    	stateTab.put("init",init);
	    	stateTab.put("listen",listen);
	    	stateTab.put("startLogic",startLogic);
	    	stateTab.put("checkInitialPosition",checkInitialPosition);
	    	stateTab.put("checkInitialSonarDistance",checkInitialSonarDistance);
	    	stateTab.put("clean",clean);
	    	stateTab.put("cleanMove",cleanMove);
	    	stateTab.put("cleanRotate",cleanRotate);
	    	stateTab.put("cleanStop",cleanStop);
	    	stateTab.put("handleSensor",handleSensor);
	    }
	    StateFun handleToutBuiltIn = () -> {	
	    	try{	
	    		PlanRepeat pr = PlanRepeat.setUp("handleTout",-1);
	    		String myselfName = "handleToutBuiltIn";  
	    		println( "webguiexecutor tout : stops");  
	    		repeatPlanNoTransition(pr,myselfName,"application_"+myselfName,false,false);
	    	}catch(Exception e_handleToutBuiltIn){  
	    		println( getName() + " plan=handleToutBuiltIn WARNING:" + e_handleToutBuiltIn.getMessage() );
	    		QActorContext.terminateQActorSystem(this); 
	    	}
	    };//handleToutBuiltIn
	    
	    StateFun init = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("init",-1);
	    	String myselfName = "init";  
	    	parg = "consult(\"./resourceModel.pl\")";
	    	//QActorUtils.solveGoal(myself,parg,pengine );  //sets currentActionResult		
	    	solveGoal( parg ); //sept2017
	    	temporaryStr = "\"Application ready\"";
	    	println( temporaryStr );  
	     connectToMqttServer("tcp://localhost:1883");
	    	//switchTo listen
	        switchToPlanAsNextState(pr, myselfName, "webguiexecutor_"+myselfName, 
	              "listen",false, false, null); 
	    }catch(Exception e_init){  
	    	 println( getName() + " plan=init WARNING:" + e_init.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//init
	    
	    StateFun listen = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp(getName()+"_listen",0);
	     pr.incNumIter(); 	
	    	String myselfName = "listen";  
	    	//bbb
	     msgTransition( pr,myselfName,"webguiexecutor_"+myselfName,false,
	          new StateFun[]{stateTab.get("startLogic"), stateTab.get("handleSensor") }, 
	          new String[]{"true","E","ctrlAppl", "true","E","sensorEvent" },
	          3600000, "handleToutBuiltIn" );//msgTransition
	    }catch(Exception e_listen){  
	    	 println( getName() + " plan=listen WARNING:" + e_listen.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//listen
	    
	    StateFun startLogic = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("startLogic",-1);
	    	String myselfName = "startLogic";  
	    	if( (guardVars = QActorUtils.evalTheGuard(this, " !?validConditions" )) != null ){
	    	{//actionseq
	    	//onEvent 
	    	setCurrentMsgFromStore(); 
	    	curT = Term.createTerm("ctrlAppl(go)");
	    	if( currentEvent != null && currentEvent.getEventId().equals("ctrlAppl") && 
	    		pengine.unify(curT, Term.createTerm("ctrlAppl(X)")) && 
	    		pengine.unify(curT, Term.createTerm( currentEvent.getMsg() ) )){ 
	    			String parg="shouldStart";
	    			/* AddRule */
	    			parg = updateVars(Term.createTerm("ctrlAppl(X)"),  Term.createTerm("ctrlAppl(go)"), 
	    				    		  					Term.createTerm(currentEvent.getMsg()), parg);
	    			if( parg != null ) addRule(parg);	    		  					
	    	}
	    	};//actionseq
	    	}
	    	else{ temporaryStr = "\"Sensors conditions invalid, cannot clean\"";
	    	println( temporaryStr );  
	    	}
	    	//switchTo checkInitialPosition
	        switchToPlanAsNextState(pr, myselfName, "webguiexecutor_"+myselfName, 
	              "checkInitialPosition",false, true, " ??shouldStart"); 
	    }catch(Exception e_startLogic){  
	    	 println( getName() + " plan=startLogic WARNING:" + e_startLogic.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//startLogic
	    
	    StateFun checkInitialPosition = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("checkInitialPosition",-1);
	    	String myselfName = "checkInitialPosition";  
	    	temporaryStr = "\"Sensors conditions are valid, checking initial position...\"";
	    	println( temporaryStr );  
	    	//bbb
	     msgTransition( pr,myselfName,"webguiexecutor_"+myselfName,true,
	          new StateFun[]{stateTab.get("checkInitialSonarDistance") }, 
	          new String[]{"true","E","sonar" },
	          1000, "listen" );//msgTransition
	    }catch(Exception e_checkInitialPosition){  
	    	 println( getName() + " plan=checkInitialPosition WARNING:" + e_checkInitialPosition.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//checkInitialPosition
	    
	    StateFun checkInitialSonarDistance = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("checkInitialSonarDistance",-1);
	    	String myselfName = "checkInitialSonarDistance";  
	    	temporaryStr = "curSonarDistance(D)";
	    	removeRule( temporaryStr );  
	    	//onEvent 
	    	setCurrentMsgFromStore(); 
	    	curT = Term.createTerm("sonar(sonar1,player,D)");
	    	if( currentEvent != null && currentEvent.getEventId().equals("sonar") && 
	    		pengine.unify(curT, Term.createTerm("sonar(SONAR,X,DISTANCE)")) && 
	    		pengine.unify(curT, Term.createTerm( currentEvent.getMsg() ) )){ 
	    			String parg="curSonarDistance(D)";
	    			/* AddRule */
	    			parg = updateVars(Term.createTerm("sonar(SONAR,X,DISTANCE)"),  Term.createTerm("sonar(sonar1,player,D)"), 
	    				    		  					Term.createTerm(currentEvent.getMsg()), parg);
	    			if( parg != null ) addRule(parg);	    		  					
	    	}
	    	//switchTo clean
	        switchToPlanAsNextState(pr, myselfName, "webguiexecutor_"+myselfName, 
	              "clean",false, true, " !?inFrontOfSonar"); 
	    }catch(Exception e_checkInitialSonarDistance){  
	    	 println( getName() + " plan=checkInitialSonarDistance WARNING:" + e_checkInitialSonarDistance.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//checkInitialSonarDistance
	    
	    StateFun clean = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("clean",-1);
	    	String myselfName = "clean";  
	    	temporaryStr = "\"Application started...\"";
	    	println( temporaryStr );  
	    	parg = "changeModelItem(blinker,on)";
	    	//QActorUtils.solveGoal(myself,parg,pengine );  //sets currentActionResult		
	    	solveGoal( parg ); //sept2017
	    	//switchTo cleanRotate
	        switchToPlanAsNextState(pr, myselfName, "webguiexecutor_"+myselfName, 
	              "cleanRotate",false, false, null); 
	    }catch(Exception e_clean){  
	    	 println( getName() + " plan=clean WARNING:" + e_clean.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//clean
	    
	    StateFun cleanMove = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp(getName()+"_cleanMove",0);
	     pr.incNumIter(); 	
	    	String myselfName = "cleanMove";  
	    	temporaryStr = QActorUtils.unifyMsgContent(pengine,"moveRobot(X)","moveRobot(w(1000))", guardVars ).toString();
	    	sendMsg("moveRobot","robot", QActorContext.dispatch, temporaryStr ); 
	    	//bbb
	     msgTransition( pr,myselfName,"webguiexecutor_"+myselfName,false,
	          new StateFun[]{stateTab.get("handleSensor"), stateTab.get("cleanStop") }, 
	          new String[]{"true","E","sensorEvent", "true","E","ctrlAppl" },
	          1000, "cleanRotate" );//msgTransition
	    }catch(Exception e_cleanMove){  
	    	 println( getName() + " plan=cleanMove WARNING:" + e_cleanMove.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//cleanMove
	    
	    StateFun cleanRotate = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp(getName()+"_cleanRotate",0);
	     pr.incNumIter(); 	
	    	String myselfName = "cleanRotate";  
	    	temporaryStr = QActorUtils.unifyMsgContent(pengine,"moveRobot(X)","moveRobot(d)", guardVars ).toString();
	    	sendMsg("moveRobot","robot", QActorContext.dispatch, temporaryStr ); 
	    	//bbb
	     msgTransition( pr,myselfName,"webguiexecutor_"+myselfName,false,
	          new StateFun[]{stateTab.get("handleSensor"), stateTab.get("cleanStop") }, 
	          new String[]{"true","E","sensorEvent", "true","E","ctrlAppl" },
	          1000, "cleanMove" );//msgTransition
	    }catch(Exception e_cleanRotate){  
	    	 println( getName() + " plan=cleanRotate WARNING:" + e_cleanRotate.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//cleanRotate
	    
	    StateFun cleanStop = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("cleanStop",-1);
	    	String myselfName = "cleanStop";  
	    	parg = "changeModelItem(blinker,off)";
	    	//QActorUtils.solveGoal(myself,parg,pengine );  //sets currentActionResult		
	    	solveGoal( parg ); //sept2017
	    	temporaryStr = QActorUtils.unifyMsgContent(pengine,"moveRobot(X)","moveRobot(h)", guardVars ).toString();
	    	sendMsg("moveRobot","robot", QActorContext.dispatch, temporaryStr ); 
	    	temporaryStr = "\"Application stopped.\"";
	    	println( temporaryStr );  
	    	//switchTo listen
	        switchToPlanAsNextState(pr, myselfName, "webguiexecutor_"+myselfName, 
	              "listen",false, false, null); 
	    }catch(Exception e_cleanStop){  
	    	 println( getName() + " plan=cleanStop WARNING:" + e_cleanStop.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//cleanStop
	    
	    StateFun handleSensor = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("handleSensor",-1);
	    	String myselfName = "handleSensor";  
	    	//onEvent 
	    	setCurrentMsgFromStore(); 
	    	curT = Term.createTerm("sensorEvent(O,P)");
	    	if( currentEvent != null && currentEvent.getEventId().equals("sensorEvent") && 
	    		pengine.unify(curT, Term.createTerm("sensorEvent(ORIGIN,PAYLOAD)")) && 
	    		pengine.unify(curT, Term.createTerm( currentEvent.getMsg() ) )){ 
	    			String parg="changeModelItem(O,P)";
	    			/* PHead */
	    			parg =  updateVars( Term.createTerm("sensorEvent(ORIGIN,PAYLOAD)"), 
	    			                    Term.createTerm("sensorEvent(O,P)"), 
	    				    		  	Term.createTerm(currentEvent.getMsg()), parg);
	    				if( parg != null ) {
	    				    aar = QActorUtils.solveGoal(this,myCtx,pengine,parg,"",outEnvView,86400000);
	    					//println(getName() + " plan " + curPlanInExec  +  " interrupted=" + aar.getInterrupted() + " action goon="+aar.getGoon());
	    					if( aar.getInterrupted() ){
	    						curPlanInExec   = "handleSensor";
	    						if( aar.getTimeRemained() <= 0 ) addRule("tout(demo,"+getName()+")");
	    						if( ! aar.getGoon() ) return ;
	    					} 			
	    					if( aar.getResult().equals("failure")){
	    						if( ! aar.getGoon() ) return ;
	    					}else if( ! aar.getGoon() ) return ;
	    				}
	    	}
	    	//switchTo cleanStop
	        switchToPlanAsNextState(pr, myselfName, "webguiexecutor_"+myselfName, 
	              "cleanStop",false, true, " not !?validConditions" 
	              ); 
	    }catch(Exception e_handleSensor){  
	    	 println( getName() + " plan=handleSensor WARNING:" + e_handleSensor.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//handleSensor
	    
	    protected void initSensorSystem(){
	    	//doing nothing in a QActor
	    }
	
	}
