/* Generated by AN DISI Unibo */ 
package it.unibo.webguiexecutor;
import it.unibo.qactors.PlanRepeat;
import it.unibo.qactors.QActorContext;
import it.unibo.qactors.StateExecMessage;
import it.unibo.qactors.QActorUtils;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.action.AsynchActionResult;
import it.unibo.qactors.action.IActorAction;
import it.unibo.qactors.action.IActorAction.ActionExecMode;
import it.unibo.qactors.action.IMsgQueue;
import it.unibo.qactors.akka.QActor;
import it.unibo.qactors.StateFun;
import java.util.Stack;
import java.util.Hashtable;
import java.util.concurrent.Callable;
import alice.tuprolog.Struct;
import alice.tuprolog.Term;
import it.unibo.qactors.action.ActorTimedAction;
public abstract class AbstractWebguiexecutor extends QActor { 
	protected AsynchActionResult aar = null;
	protected boolean actionResult = true;
	protected alice.tuprolog.SolveInfo sol;
	protected String planFilePath    = null;
	protected String terminationEvId = "default";
	protected String parg="";
	protected boolean bres=false;
	protected IActorAction action;
	 
	
		protected static IOutputEnvView setTheEnv(IOutputEnvView outEnvView ){
			return outEnvView;
		}
		public AbstractWebguiexecutor(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
			super(actorId, myCtx,  
			"./srcMore/it/unibo/webguiexecutor/WorldTheory.pl",
			setTheEnv( outEnvView )  , "init");
			this.planFilePath = "./srcMore/it/unibo/webguiexecutor/plans.txt";
	  	}
		@Override
		protected void doJob() throws Exception {
			String name  = getName().replace("_ctrl", "");
			mysupport = (IMsgQueue) QActorUtils.getQActor( name ); 
			initStateTable(); 
	 		initSensorSystem();
	 		history.push(stateTab.get( "init" ));
	  	 	autoSendStateExecMsg();
	  		//QActorContext.terminateQActorSystem(this);//todo
		} 	
		/* 
		* ------------------------------------------------------------
		* PLANS
		* ------------------------------------------------------------
		*/    
	    //genAkkaMshHandleStructure
	    protected void initStateTable(){  	
	    	stateTab.put("handleToutBuiltIn",handleToutBuiltIn);
	    	stateTab.put("init",init);
	    	stateTab.put("listen",listen);
	    	stateTab.put("startLogic",startLogic);
	    	stateTab.put("printEv",printEv);
	    	stateTab.put("handleSensor",handleSensor);
	    }
	    StateFun handleToutBuiltIn = () -> {	
	    	try{	
	    		PlanRepeat pr = PlanRepeat.setUp("handleTout",-1);
	    		String myselfName = "handleToutBuiltIn";  
	    		println( "webguiexecutor tout : stops");  
	    		repeatPlanNoTransition(pr,myselfName,"application_"+myselfName,false,false);
	    	}catch(Exception e_handleToutBuiltIn){  
	    		println( getName() + " plan=handleToutBuiltIn WARNING:" + e_handleToutBuiltIn.getMessage() );
	    		QActorContext.terminateQActorSystem(this); 
	    	}
	    };//handleToutBuiltIn
	    
	    StateFun init = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("init",-1);
	    	String myselfName = "init";  
	    	temporaryStr = "\"Application ready\"";
	    	println( temporaryStr );  
	     connectToMqttServer("tcp://localhost:1883");
	    	//switchTo listen
	        switchToPlanAsNextState(pr, myselfName, "webguiexecutor_"+myselfName, 
	              "listen",false, false, null); 
	    }catch(Exception e_init){  
	    	 println( getName() + " plan=init WARNING:" + e_init.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//init
	    
	    StateFun listen = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp(getName()+"_listen",0);
	     pr.incNumIter(); 	
	    	String myselfName = "listen";  
	    	//bbb
	     msgTransition( pr,myselfName,"webguiexecutor_"+myselfName,false,
	          new StateFun[]{stateTab.get("startLogic"), stateTab.get("printEv"), stateTab.get("printEv"), stateTab.get("handleSensor") }, 
	          new String[]{"true","M","startAppl", "true","E","sonar", "true","E","sonarDetect", "true","E","sensorEvent" },
	          3600000, "handleToutBuiltIn" );//msgTransition
	    }catch(Exception e_listen){  
	    	 println( getName() + " plan=listen WARNING:" + e_listen.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//listen
	    
	    StateFun startLogic = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("startLogic",-1);
	    	String myselfName = "startLogic";  
	    	temporaryStr = "\"Application started...\"";
	    	println( temporaryStr );  
	    	//delay  ( no more reactive within a plan)
	    	aar = delayReactive(1000,"" , "");
	    	if( aar.getInterrupted() ) curPlanInExec   = "startLogic";
	    	if( ! aar.getGoon() ) return ;
	    	temporaryStr = QActorUtils.unifyMsgContent(pengine, "ctrlEvent(TARGET,PAYLOAD)","ctrlEvent(hueLamp,on)", guardVars ).toString();
	    	emit( "ctrlEvent", temporaryStr );
	    	//delay  ( no more reactive within a plan)
	    	aar = delayReactive(2000,"" , "");
	    	if( aar.getInterrupted() ) curPlanInExec   = "startLogic";
	    	if( ! aar.getGoon() ) return ;
	    	temporaryStr = QActorUtils.unifyMsgContent(pengine, "ctrlEvent(TARGET,PAYLOAD)","ctrlEvent(hueLamp,off)", guardVars ).toString();
	    	emit( "ctrlEvent", temporaryStr );
	    	temporaryStr = "\"Application done!\"";
	    	println( temporaryStr );  
	    	repeatPlanNoTransition(pr,myselfName,"webguiexecutor_"+myselfName,false,true);
	    }catch(Exception e_startLogic){  
	    	 println( getName() + " plan=startLogic WARNING:" + e_startLogic.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//startLogic
	    
	    StateFun printEv = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("printEv",-1);
	    	String myselfName = "printEv";  
	    	printCurrentEvent(false);
	    	repeatPlanNoTransition(pr,myselfName,"webguiexecutor_"+myselfName,false,true);
	    }catch(Exception e_printEv){  
	    	 println( getName() + " plan=printEv WARNING:" + e_printEv.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//printEv
	    
	    StateFun handleSensor = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("handleSensor",-1);
	    	String myselfName = "handleSensor";  
	    	//onEvent 
	    	setCurrentMsgFromStore(); 
	    	curT = Term.createTerm("sensorEvent(O,P)");
	    	if( currentEvent != null && currentEvent.getEventId().equals("sensorEvent") && 
	    		pengine.unify(curT, Term.createTerm("sensorEvent(ORIGIN,PAYLOAD)")) && 
	    		pengine.unify(curT, Term.createTerm( currentEvent.getMsg() ) )){ 
	    			String parg = "sensorEvent(O,P)";
	    			/* Print */
	    			parg =  updateVars( Term.createTerm("sensorEvent(ORIGIN,PAYLOAD)"), 
	    			                    Term.createTerm("sensorEvent(O,P)"), 
	    				    		  	Term.createTerm(currentEvent.getMsg()), parg);
	    			if( parg != null ) println( parg );
	    	}
	    	repeatPlanNoTransition(pr,myselfName,"webguiexecutor_"+myselfName,false,true);
	    }catch(Exception e_handleSensor){  
	    	 println( getName() + " plan=handleSensor WARNING:" + e_handleSensor.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//handleSensor
	    
	    protected void initSensorSystem(){
	    	//doing nothing in a QActor
	    }
	
	}
