/* Generated by AN DISI Unibo */ 
package it.unibo.webguiexecutor;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Webguiexecutor extends QActorMsgQueue{
	public MsgHandle_Webguiexecutor(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
